In [18]:
import numpy as np





__1.__ Найдите собственные векторы и собственные значения для линейного оператора, заданного матрицей:

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей:

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Покажите, что __любой__ вектор считается для него собственным.

__3.__ Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установите, считается ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

**4.** Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установите, считается ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

№1

$$
A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix} 
\newline
|A - \lambda E| = 0 =>
\begin{vmatrix}
-1 - \lambda & -6\\ 
2 & 6 - \lambda
\end{vmatrix} = -6 - 5\lambda + \lambda^2 + 12 = 
\lambda^2 - 5\lambda + 6 = (\lambda - 2)(\lambda - 3) = 0 
\newline
\begin{cases}
\lambda_1 = 2
\\
\lambda_2 = 3
\end{cases}
$$

Найдем собственные вектор матрицы $A$ соответствующий собственному значению $\lambda_1 = 2$:  

$$
\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix} 
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix} = 
2\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix} =>
\begin{cases}
-3 x_1 - 6 x_2 = 0
\\
2 x_1 + 4 x_2 = 0
\end{cases} =>
x_1 = -2x_2
$$
Тогда собственный вектор соответствующий собственному значению $\lambda_1 = 2$ будет равен $v1 = 
\begin{pmatrix}
-2\\ 
1
\end{pmatrix}$

Найдем собственные вектор матрицы $A$ соответствующий собственному значению $\lambda_2 = 3$:  
$$
\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix} 
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix} = 
3\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix} =>
\begin{cases}
-4 x_1 - 6 x_2 = 0
\\
2 x_1 + 3 x_2 = 0
\end{cases} =>
x_1 = -1.5x_2
$$
Найдем собственные вектор матрицы $A$ соответствующий собственному значению $\lambda_2 = 3:  
\begin{pmatrix}
1.5\\ 
-1
\end{pmatrix}$

№2

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Собственные значения данной матрицы будут равны $\lambda_1 = \lambda_2 = -1$

Тогда собственные векторы данной матрицы будут иметь вид:
$$
v1 = \begin{pmatrix}
x_1 = 0\\
x_2 \in R
\end{pmatrix}
\newline
v2 = \begin{pmatrix}
x_1 \in R\\
x_2 = 0
\end{pmatrix}
$$


In [20]:
np.dot([[-1, 0], [0, -1]], [3, 4])

array([-3, -4])

№3

In [32]:
A =[[1, 1], [-1, 3]]
print("Собственные значения:", np.round(np.linalg.eigvals(A), 2))
np.dot(A, [1, 1])

Собственные значения: [2. 2.]


array([2, 2])

$A x = \lambda x => $ данный вектор является собственным для данной матрицы.

№4

In [35]:
A =[[0, 3, 0],[3, 0, 0],[0, 0, 3]]
print("Собственные значения:", np.round(np.linalg.eigvals(A), 2))
np.dot(A, [3, -3, -4])

Собственные значения: [ 3. -3.  3.]


array([ -9,   9, -12])

Данный вектор не является собственным.

In [38]:
np.linalg.eigh(A)

(array([-3.,  3.,  3.]),
 array([[-0.70710678,  0.70710678,  0.        ],
        [ 0.70710678,  0.70710678,  0.        ],
        [ 0.        ,  0.        ,  1.        ]]))