__1.__ Решите систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

__2.__ Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$


__3.__ Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

__4.__ Дана система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найдите соотношение между параметрами $a$, $b$ и $c$, при которых система считается несовместной.

№1

$$
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -1\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix} = 
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -1\\ 
0 & -1 & 1 & 3\\ 
0 & 0 & -2 & 2
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}
$$

Данная СЛАУ неопределенная и имеет бесконечное количество решений.

№2

а) $$\begin{cases}
3x_{1}-x_{2}+x_{3}=4 \\
2x_{1}-5x_{2}-3x_{3}=-17 \\
x_{1}+x_{2}-x_{3}=0
\end{cases} =>
\begin{cases}
4x_{1}=4 \\
-x_{1}-8x_{2}=-17 \\
x_{1}+x_{2}-x_{3}=0
\end{cases} =>
\begin{cases}
x_{1}=1 \\
-8x_{2}=-16 \\
1+x_{2}-x_{3}=0
\end{cases} =>
\begin{cases}
x_{1}=1 \\
x_{2}=-2 \\
1+x_{2}-x_{3}=0
\end{cases} =>
\begin{cases}
x_{1}=1 \\
x_{2}=-2 \\
x_{3}=-1
\end{cases}
$$

б) Ранг расширенной матрицы не равен рангу основной матрицы, значит система несовместна.

в) Данная СЛАУ неопределенная и имеет бесконечное количество решений.

№3

Ранг основной матрицы равен рангу расширенной, СЛАУ имеет единственное решение:
$$
\begin{cases}
x_{1}=\frac{83}{30} \\
x_{2}=\frac{3}{10} \\
x_{3}=\frac{4}{3}\\
x_{4}=\frac{1}{2}
\end{cases}
$$

№4

In [1]:
import numpy as np

In [8]:
np.round(np.linalg.det([[1,2,3],[4,5,6],[7,8,9]]), 8)

0.0

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix} \sim 
\begin{pmatrix}
\left.\begin{matrix}
7 & 8 & 9\\ 
0 & \frac{6}{7} & \frac{12}{7}\\ 
0 & 0 & 0 
\end{matrix}\right|
\begin{matrix}
z\\ 
x - \frac{z}{7}\\
y - \frac{4 z}{7} + \frac{-x + \frac{z}{7}}{2}
\end{matrix}
\end{pmatrix}
$$

Чтобы система была несовместной, выражение $y - \frac{4 z}{7} + \frac{-x + \frac{z}{7}}{2}$ должно быть не равно нулю.

__1.__ Решите систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

__2*.__ Найдите $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    
__3*.__ Решите систему линейных уравнений методом $LU$-разложения:

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

__4*.__ Решите систему линейных уравнений методом Холецкого:

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

__5*.__ Напишите на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

1.a)

In [10]:
d = np.linalg.det([[1, -2],[3, -4]])
d1 = np.linalg.det([[1, -2],[7, -4]])
d2 = np.linalg.det([[1, 1],[3, 7]])

In [13]:
np.round(d1 / d, 6)

5.0

In [14]:
np.round(d2 / d, 6)

2.0

x_1 = 5, x_2 = 2

1.b)

In [15]:
d = np.linalg.det([[2, -1, 5],[1, 1, -3], [2, 4, 1]])
d1 = np.linalg.det([[10, -1, 5],[-2, 1, -3], [1, 4, 1]])
d2 = np.linalg.det([[2, 10, 5],[1, -2, -3], [2, 1, 1]])
d3 = np.linalg.det([[2, -1, 10],[1, 1, -2], [2, 4, 1]])
d

42.99999999999998

In [16]:
np.round(d1 / d, 6)

2.0

In [17]:
np.round(d2 / d, 6)

-1.0

In [18]:
np.round(d3 / d, 6)

1.0

x_1 = 2, x_2 = -1, x_3 = 1

№2

a)

Матрица коеффициентов:
$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix} \sim
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix} \sim
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}
$$

Матрица $L$:

$$\begin{pmatrix}
1 & 0 & 0 \\ 
l_{21} & 1 & 0 \\ 
l_{31} & l_{32} & 1
\end{pmatrix} \sim
\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix} \sim
\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}
$$

b) 

Матрица коеффициентов:
$$
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix} \sim
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix} \sim
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix} \sim 
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}
$$
Матрица $L$:
$$
\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
l_{21} & 1 & 0 & 0 \\ 
l_{31} & l_{32} & 1 & 0\\ 
l_{41} & l_{42} & l_{43} & 1
\end{pmatrix} \sim
\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & l_{32} & 1 & 0\\ 
4 & l_{42} & l_{43} & 1
\end{pmatrix} \sim
\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0\\ 
4 & 6 & l_{43} & 1
\end{pmatrix} \sim 
\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0\\ 
4 & 6 & 7 & 1
\end{pmatrix}
$$

№3

b = (1, -6, -5)

In [5]:
from scipy.linalg import lu

In [11]:
A = [[2, 1, 3],[11, 7, 5],[9, 8, 4]]
b = 1, -6, -5

In [8]:
P, L, U = lu(A)

In [9]:
L

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.81818182,  1.        ,  0.        ],
       [ 0.18181818, -0.12      ,  1.        ]])

In [10]:
U

array([[11.        ,  7.        ,  5.        ],
       [ 0.        ,  2.27272727, -0.09090909],
       [ 0.        ,  0.        ,  2.08      ]])

$Ly=b:$

In [13]:
y = np.linalg.solve(L, b)
y

array([ 1.        , -6.81818182, -6.        ])

In [14]:
x = np.linalg.solve(U, y)
x

array([ 3.38461538, -3.11538462, -2.88461538])

In [15]:
np.dot(A, x)

array([-5.,  1., -6.])

№5

https://github.com/Setom29/Programming/tree/master/Numerical%20methods/py_numerical_methods/num_methods_with_numpy