In [1]:
import numpy as np
import pandas as pd

# Теория вероятностей и математическая статистика

## Урок 7

## Линейная регрессия. Двухвыборочный t-тест. A/B-тестирование

### Домашнее задание

В поле ответа впишите одно число. Нецелые числа следует округлить до 8 знаков после запятой.

__Задача 1__

Дана матрица объект-признак
```
X = [[ 1.22401313,  2.30868478,  3.03636353,  2.69287214],
     [-0.18757272,  1.30337355,  5.12093014,  3.46363202],
     [-0.81094525,  1.82463398,  5.79686488,  1.86159445],
     [ 0.75129018,  2.67392052,  3.65529809,  1.66746094],
     [ 0.00972362,  1.97367255,  2.50594319,  1.69755173],
     [-0.62972637,  0.77750764,  2.84124027,  4.54410559],
     [ 2.29536229,  1.81206697,  1.95026215,  1.51874636],
     [ 0.0920418 ,  2.26971361,  7.47708735,  2.61081203],
     [ 2.39252799,  3.17563985,  3.61420599,  5.10773362],
     [ 0.54983815,  2.87988651,  1.65752765,  1.59635987]]
```
и значения целевой переменной
```
y = [ 9.26193358,  9.700363  ,  8.67214805,  8.74796974,  6.18689108,
      7.53312713,  7.57643777, 12.44965478, 14.29010746,  6.68361218]
```

Подберите два признака (из четырёх) так, чтобы уровень линейной зависимости целевой переменной от значений этих признаков был максимальным. Другими словами, модель линейной регрессии на этих признаках должна давать наилучший результат. В качестве ответа запишите значение коэффициента детерминации для модели на этих признаках.

In [2]:
X = np.array([[ 1.22401313,  2.30868478,  3.03636353,  2.69287214],
     [-0.18757272,  1.30337355,  5.12093014,  3.46363202],
     [-0.81094525,  1.82463398,  5.79686488,  1.86159445],
     [ 0.75129018,  2.67392052,  3.65529809,  1.66746094],
     [ 0.00972362,  1.97367255,  2.50594319,  1.69755173],
     [-0.62972637,  0.77750764,  2.84124027,  4.54410559],
     [ 2.29536229,  1.81206697,  1.95026215,  1.51874636],
     [ 0.0920418 ,  2.26971361,  7.47708735,  2.61081203],
     [ 2.39252799,  3.17563985,  3.61420599,  5.10773362],
     [ 0.54983815,  2.87988651,  1.65752765,  1.59635987]])
y = np.array([ 9.26193358,  9.700363  ,  8.67214805,  8.74796974,  6.18689108,
      7.53312713,  7.57643777, 12.44965478, 14.29010746,  6.68361218])

In [3]:
def sum_of_squares(samples: np.ndarray) -> float:
    """Сумма квадратов отклонений.
    """
    
    return ((samples - samples.mean()) ** 2).sum()

In [4]:
x1 = X[:,[0, 2]]
ones = np.ones((x1.shape[0], 1))
x1 = np.hstack((ones, x1))
x1

array([[ 1.        ,  1.22401313,  3.03636353],
       [ 1.        , -0.18757272,  5.12093014],
       [ 1.        , -0.81094525,  5.79686488],
       [ 1.        ,  0.75129018,  3.65529809],
       [ 1.        ,  0.00972362,  2.50594319],
       [ 1.        , -0.62972637,  2.84124027],
       [ 1.        ,  2.29536229,  1.95026215],
       [ 1.        ,  0.0920418 ,  7.47708735],
       [ 1.        ,  2.39252799,  3.61420599],
       [ 1.        ,  0.54983815,  1.65752765]])

In [5]:
XTX = x1.T.dot(x1)
XTX

array([[ 10.        ,   5.68655282,  37.65572324],
       [  5.68655282,  14.45578256,  13.75963817],
       [ 37.65572324,  13.75963817, 172.28091363]])

In [6]:
XTX_inv = np.linalg.inv(XTX)

b = XTX_inv.dot(x1.T).dot(y)

print(b)

[3.62455695 1.62531203 1.21134979]


In [7]:
z = x1.dot(b)
e = y - z

e

array([-0.03012497,  0.17743258, -0.6564009 , -0.52551276, -0.48904355,
        1.49033621, -2.14124878, -0.38186703,  2.3988783 ,  0.15755089])

In [14]:
R = 1 - sum_of_squares(e) / sum_of_squares(y)
print(f"Ответ: {R}")

Ответ: 0.7634246238793152


__Задача 2__

Является ли значимым уравнение регрессии, полученное в предыдущей задаче? В качестве ответа запишите 1, если является, и 0 иначе.

In [9]:
n = x1.shape[0]
m = x1.shape[1] - 1

k1 = m
k2 = n - m - 1

In [10]:
from scipy import stats

In [11]:
alpha = 0.05

t = stats.f.ppf(1 - alpha, k1, k2)
t

4.73741412777588

Критическая область имеет вид:
$$\Omega_\alpha =(4.74, +\infty)$$

In [12]:
F = (R / k1) / ((1 - R) / k2)
print(f'{F}\nОтвет: 1')

11.29443912292265
Ответ: 1


__Задача 3__

Для проведения A/B-тестирования сайта интернет-магазина были получены следующие данные: страница `A` была посещена 2509 раз, из них 77 закончились совершением покупки, страница `B` была посещена 1465 раз, 60 из них закончились совершением покупки. Является ли значимым отличие конверсии на страницах `A` и `B`? В качестве ответа запишите 1, если является, и 0 иначе.

_Подсказка_. Реализуйте двухвыборочный t-тест. В качестве выборок здесь можно взять наборы меток совершения покупки (0 или 1) каждым посетителем.

In [15]:
from random import shuffle

In [16]:
arr1 = [0 for i in range(2509 - 77)] + [1 for i in range(77)]
arr2 = [0 for i in range(1465 - 60)] + [1 for i in range(60)]
shuffle(arr1)
shuffle(arr2)
arr1 = np.array(arr1)
arr2 = np.array(arr2)



In [17]:
n1 = arr1.size
n2 = arr2.size

s1 = arr1.std(ddof=1)
s2 = arr2.std(ddof=1)
n1, n2

(2509, 1465)

In [18]:
s_delta = np.sqrt(s1 ** 2 / n1 + s2 ** 2 / n2)
s_delta

0.006220171278295827

In [19]:
t = (arr1.mean() - arr2.mean()) / s_delta

t

-1.6504551408398205

In [20]:
df = (s1 ** 2 / n1 + s2 ** 2 / n2) ** 2 / \
    ((s1 ** 2 / n1) ** 2 / (n1 - 1) + (s2 ** 2 / n2) ** 2 / (n2 - 1))

df

2732.802564435212

In [21]:
alpha = 0.05

t1 = stats.t.ppf(alpha / 2, df=df)
t2 = stats.t.ppf(1 - alpha / 2, df=df)

t1, t2

(-1.9608324352746576, 1.9608324352746571)

Критическая область имеет вид:
$$\Omega_\alpha = (-\infty, -1.96) \cup (1.96, +\infty)$$

In [22]:
stats.ttest_ind(arr1, arr2, equal_var=False)

Ttest_indResult(statistic=-1.6504551408398205, pvalue=0.09896479217925899)

Значение статистики не попало в критическую область, значит отличие конверсии на страницах `A` и `B` не является значимым.  
__Ответ:__ 0