In [7]:
import torch
import random

In [40]:
# Создайте случайный FloatTensor размера 3x4x5
a = torch.randn(3,4,5)
a
print(a, "\n", a.type())

tensor([[[ 1.2223, -2.4738,  0.2368,  0.1028, -1.1028],
         [-0.0725, -0.0715, -0.4823, -0.4666,  0.5153],
         [ 0.8175,  1.0441,  1.3559,  1.2605,  0.0789],
         [ 0.0387,  0.5497, -0.5479,  1.4912,  0.0511]],

        [[ 0.5453,  0.5474,  1.5096,  1.0679, -1.7353],
         [ 0.7958,  0.1236,  0.8463, -0.3605, -0.2991],
         [-0.2234, -0.3398, -1.6848,  2.2865,  0.0675],
         [ 0.3898,  1.0703, -0.0295,  2.1852,  1.0654]],

        [[-0.9223, -0.7779,  1.2577, -0.9109, -1.5095],
         [ 1.8022, -1.5428, -1.1768, -0.9345,  0.1927],
         [-0.2694, -0.7566,  0.1383, -1.4642, -1.0158],
         [ 0.6135, -0.1494,  0.8534,  0.2335,  0.3243]]]) 
 torch.FloatTensor


In [41]:
# Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [42]:
# Приведите его к форме 6 X 10
a = a.reshape((6, 10))
a

tensor([[ 1.2223, -2.4738,  0.2368,  0.1028, -1.1028, -0.0725, -0.0715, -0.4823,
         -0.4666,  0.5153],
        [ 0.8175,  1.0441,  1.3559,  1.2605,  0.0789,  0.0387,  0.5497, -0.5479,
          1.4912,  0.0511],
        [ 0.5453,  0.5474,  1.5096,  1.0679, -1.7353,  0.7958,  0.1236,  0.8463,
         -0.3605, -0.2991],
        [-0.2234, -0.3398, -1.6848,  2.2865,  0.0675,  0.3898,  1.0703, -0.0295,
          2.1852,  1.0654],
        [-0.9223, -0.7779,  1.2577, -0.9109, -1.5095,  1.8022, -1.5428, -1.1768,
         -0.9345,  0.1927],
        [-0.2694, -0.7566,  0.1383, -1.4642, -1.0158,  0.6135, -0.1494,  0.8534,
          0.2335,  0.3243]])

In [45]:
# Создайте случайный IntTensor размера 10
b = torch.rand(10)
b

tensor([0.5059, 0.3751, 0.7742, 0.1942, 0.0959, 0.0042, 0.6079, 0.4868, 0.2039,
        0.5859])

In [46]:
# Умножьте созданный FloatTensor на созданный IntTensor поэлементно
a*b

tensor([[ 6.1836e-01, -9.2805e-01,  1.8335e-01,  1.9958e-02, -1.0577e-01,
         -3.0343e-04, -4.3486e-02, -2.3475e-01, -9.5137e-02,  3.0196e-01],
        [ 4.1358e-01,  3.9171e-01,  1.0497e+00,  2.4479e-01,  7.5686e-03,
          1.6190e-04,  3.3420e-01, -2.6669e-01,  3.0404e-01,  2.9917e-02],
        [ 2.7588e-01,  2.0537e-01,  1.1688e+00,  2.0739e-01, -1.6645e-01,
          3.3306e-03,  7.5119e-02,  4.1195e-01, -7.3498e-02, -1.7526e-01],
        [-1.1301e-01, -1.2746e-01, -1.3044e+00,  4.4403e-01,  6.4765e-03,
          1.6316e-03,  6.5067e-01, -1.4379e-02,  4.4554e-01,  6.2428e-01],
        [-4.6663e-01, -2.9184e-01,  9.7376e-01, -1.7689e-01, -1.4479e-01,
          7.5428e-03, -9.3789e-01, -5.7281e-01, -1.9054e-01,  1.1289e-01],
        [-1.3631e-01, -2.8383e-01,  1.0710e-01, -2.8435e-01, -9.7429e-02,
          2.5677e-03, -9.0822e-02,  4.1540e-01,  4.7609e-02,  1.9004e-01]])

In [57]:
a

tensor([[ 1.2223, -2.4738,  0.2368,  0.1028, -1.1028, -0.0725, -0.0715, -0.4823,
         -0.4666,  0.5153],
        [ 0.8175,  1.0441,  1.3559,  1.2605,  0.0789,  0.0387,  0.5497, -0.5479,
          1.4912,  0.0511],
        [ 0.5453,  0.5474,  1.5096,  1.0679, -1.7353,  0.7958,  0.1236,  0.8463,
         -0.3605, -0.2991],
        [-0.2234, -0.3398, -1.6848,  2.2865,  0.0675,  0.3898,  1.0703, -0.0295,
          2.1852,  1.0654],
        [-0.9223, -0.7779,  1.2577, -0.9109, -1.5095,  1.8022, -1.5428, -1.1768,
         -0.9345,  0.1927],
        [-0.2694, -0.7566,  0.1383, -1.4642, -1.0158,  0.6135, -0.1494,  0.8534,
          0.2335,  0.3243]])

In [72]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти
c = a.mm(a.T)
print(c, "\n", c.shape)

tensor([[ 9.6228, -1.6676,  1.2325, -0.2321,  3.7486,  2.1575],
        [-1.6676,  8.0222,  3.3557,  3.9984, -2.6456, -2.9097],
        [ 1.2325,  3.3557,  8.6120, -1.2155,  3.1435,  0.8576],
        [-0.2321,  3.9984, -1.2155, 15.4452, -6.5841, -2.4225],
        [ 3.7486, -2.6456,  3.1435, -6.5841, 14.0695,  4.0542],
        [ 2.1575, -2.9097,  0.8576, -2.4225,  4.0542,  5.1265]]) 
 torch.Size([6, 6])


In [93]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x = torch.tensor([1.0], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.0], requires_grad=True)
y = (x**3 + z - 75*t).sum()
print(y)
y.backward()
print(x.grad, z.grad, t.grad)


tensor(-148.5000, grad_fn=<SumBackward0>)
tensor([3.]) tensor([1.]) tensor([-75.])


In [95]:
# Создайте единичный тензор размера 5x6
d = torch.ones((5, 6))
d

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [96]:
# Переведите его в формат numpy
d.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)